# Site settings
title: Modern Blog
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun
author: Wferr
baseurl: "/rolycoaster" # the subpath of your site, e.g. /blog/
url: "rolycoaster.com" # the base hostname & protocol for your site
