# Site settings
title: Posh Mom Blog
description: An Educator Transitioning Fully Online
keywords: Modern, Blogging, Fun, MATh, Science, tutor, posh tutor, posh mom, baby, EsL, English Second Language, Fit, Home
author: Wferr
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
