# Site settings
title: Rolycoaster
description: A Blog To Keep Track
keywords: Modern, Blogging, Fun
author: Rolycoaster
baseurl: "/rolycoaster" # the subpath of your site, e.g. /blog/
url: "https://rolycoaster.com" # the base hostname & protocol for your site
