# Site settings
title: Kid Toy Shop
description: Modern-Blog A Elegant template for Jekyll
keywords: Kid toy, Đồ chơi trẻ em, do choi tre em
author: Wferr
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
