# Site settings
title: Subwai Blog
description: Subwai-Blog
keywords: Support, Bot, AI
author: Subwai
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
