# Site settings
title: Rolynda
description: Short Stories
keywords: Short stories, writing, memoirs
author: Rolynda
baseurl: "/rolynda" # the subpath of your site, e.g. /blog/
url: "https://rolynda.com" # the base hostname & protocol for your site
