# Site settings
title: "Siner's Blog"
description: Backend Developer / Hardstyle DJ
keywords: Developer, Backend, DevOps, Hardstyle, DJ, EDM
author: Siner
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://siner308.github.io" # the base hostname & protocol for your site
